name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: npm install
      run: |
        npm install
    - name: npm test
      run: |
        npm test
      env:
        CI: true
